[mongodb]
mongodb.jansi.fun

[redis]
redis.jansi.fun

[rabbitmq]
rabbitmq.jansi.fun

[mysql]
mysql.jansi.fun

[catalogue]
catalogue.jansi.fun

[user]
user.jansi.fun

[cart]
cart.jansi.fun

[shipping]
shipping.jansi.fun

[payment]
payment.jansi.fun

[frontend]
frontend.jansi.fun


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local]
localhost ansible_connection=local
; do not SSH, run directly on my Mac
